# Generated by Django 5.0.6 on 2024-06-02 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0013_alter_doctor_id_alter_expertize_id_alter_faq_id_and_more'),
        ('hospital', '0014_child_vaccination'),
    ]

    operations = [
    ]
